---
title: "N-Mixture model by group"
author: "Shuhan Song"
date: "12/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r, include=FALSE}
# read in parameters
source("parameters.R", local = knitr::knit_global())
```

```{r}
# clean Timelapse output CSV file (run this R script)
source("00_cleaning_camera_trap_pig_count.R", local = knitr::knit_global())
```

Summary of the model:

```{r}
# N-mixture model by group (run this R script)
source("01_n_mixture_model_by_group.R", local = knitr::knit_global())

# convert estimated number of group to pig abundance per site (run this R script)
source("01_number_of_groups_to_abundance.R", local = knitr::knit_global())
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
```

The detection probability is `r round(detect_prop_n_mixture*100, 2)`%.

Estimated number of groups of pigs and corresponding pig abundance from `r as.character(readr::parse_number(gsub("_", "", begin_visit)))` to `r as.character(readr::parse_number(gsub("_", "", end_visit)))` are:

```{r, echo=FALSE}
kableExtra::kable(site_abundance,
      col.names = c("Camera station", 
                    "Number of groups", 
                    "Weighted average of group size",
                    "Estimated pig abundance",
                    "Starting date", 
                    "Ending date"),
      digits = 2) %>% 
  kable_styling(full_width = TRUE)
```

